# Generated by Django 3.1.3 on 2021-01-17 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0005_auto_20210116_0427'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
