# Generated by Django 3.1.3 on 2021-01-25 04:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tracker_app', '0008_auto_20210124_1257'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('user', 'date_registered')},
        ),
    ]
