# Generated by Django 3.1.3 on 2021-01-25 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0009_auto_20210124_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unsubscribed',
            field=models.BooleanField(default=False),
        ),
    ]
